# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp/CMakeFiles /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AlphaZero_TTT

# Build rule for target.
AlphaZero_TTT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AlphaZero_TTT
.PHONY : AlphaZero_TTT

# fast build rule for target.
AlphaZero_TTT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/build
.PHONY : AlphaZero_TTT/fast

board.o: board.cpp.o
.PHONY : board.o

# target to build an object file
board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/board.cpp.o
.PHONY : board.cpp.o

board.i: board.cpp.i
.PHONY : board.i

# target to preprocess a source file
board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/board.cpp.i
.PHONY : board.cpp.i

board.s: board.cpp.s
.PHONY : board.s

# target to generate assembly for a file
board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/board.cpp.s
.PHONY : board.cpp.s

cell_state.o: cell_state.cpp.o
.PHONY : cell_state.o

# target to build an object file
cell_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/cell_state.cpp.o
.PHONY : cell_state.cpp.o

cell_state.i: cell_state.cpp.i
.PHONY : cell_state.i

# target to preprocess a source file
cell_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/cell_state.cpp.i
.PHONY : cell_state.cpp.i

cell_state.s: cell_state.cpp.s
.PHONY : cell_state.s

# target to generate assembly for a file
cell_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/cell_state.cpp.s
.PHONY : cell_state.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game.cpp.s
.PHONY : game.cpp.s

inference_client.o: inference_client.cpp.o
.PHONY : inference_client.o

# target to build an object file
inference_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/inference_client.cpp.o
.PHONY : inference_client.cpp.o

inference_client.i: inference_client.cpp.i
.PHONY : inference_client.i

# target to preprocess a source file
inference_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/inference_client.cpp.i
.PHONY : inference_client.cpp.i

inference_client.s: inference_client.cpp.s
.PHONY : inference_client.s

# target to generate assembly for a file
inference_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/inference_client.cpp.s
.PHONY : inference_client.cpp.s

inference_queue_shm.o: inference_queue_shm.cpp.o
.PHONY : inference_queue_shm.o

# target to build an object file
inference_queue_shm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/inference_queue_shm.cpp.o
.PHONY : inference_queue_shm.cpp.o

inference_queue_shm.i: inference_queue_shm.cpp.i
.PHONY : inference_queue_shm.i

# target to preprocess a source file
inference_queue_shm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/inference_queue_shm.cpp.i
.PHONY : inference_queue_shm.cpp.i

inference_queue_shm.s: inference_queue_shm.cpp.s
.PHONY : inference_queue_shm.s

# target to generate assembly for a file
inference_queue_shm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/inference_queue_shm.cpp.s
.PHONY : inference_queue_shm.cpp.s

logger.o: logger.cpp.o
.PHONY : logger.o

# target to build an object file
logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/logger.cpp.o
.PHONY : logger.cpp.o

logger.i: logger.cpp.i
.PHONY : logger.i

# target to preprocess a source file
logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/logger.cpp.i
.PHONY : logger.cpp.i

logger.s: logger.cpp.s
.PHONY : logger.s

# target to generate assembly for a file
logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/logger.cpp.s
.PHONY : logger.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/main.cpp.s
.PHONY : main.cpp.s

mcts_agent_selfplay.o: mcts_agent_selfplay.cpp.o
.PHONY : mcts_agent_selfplay.o

# target to build an object file
mcts_agent_selfplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/mcts_agent_selfplay.cpp.o
.PHONY : mcts_agent_selfplay.cpp.o

mcts_agent_selfplay.i: mcts_agent_selfplay.cpp.i
.PHONY : mcts_agent_selfplay.i

# target to preprocess a source file
mcts_agent_selfplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/mcts_agent_selfplay.cpp.i
.PHONY : mcts_agent_selfplay.cpp.i

mcts_agent_selfplay.s: mcts_agent_selfplay.cpp.s
.PHONY : mcts_agent_selfplay.s

# target to generate assembly for a file
mcts_agent_selfplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/mcts_agent_selfplay.cpp.s
.PHONY : mcts_agent_selfplay.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/player.cpp.s
.PHONY : player.cpp.s

position_pool.o: position_pool.cpp.o
.PHONY : position_pool.o

# target to build an object file
position_pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/position_pool.cpp.o
.PHONY : position_pool.cpp.o

position_pool.i: position_pool.cpp.i
.PHONY : position_pool.i

# target to preprocess a source file
position_pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/position_pool.cpp.i
.PHONY : position_pool.cpp.i

position_pool.s: position_pool.cpp.s
.PHONY : position_pool.s

# target to generate assembly for a file
position_pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/position_pool.cpp.s
.PHONY : position_pool.cpp.s

training_shm_writer.o: training_shm_writer.cpp.o
.PHONY : training_shm_writer.o

# target to build an object file
training_shm_writer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/training_shm_writer.cpp.o
.PHONY : training_shm_writer.cpp.o

training_shm_writer.i: training_shm_writer.cpp.i
.PHONY : training_shm_writer.i

# target to preprocess a source file
training_shm_writer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/training_shm_writer.cpp.i
.PHONY : training_shm_writer.cpp.i

training_shm_writer.s: training_shm_writer.cpp.s
.PHONY : training_shm_writer.s

# target to generate assembly for a file
training_shm_writer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/training_shm_writer.cpp.s
.PHONY : training_shm_writer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AlphaZero_TTT"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... cell_state.o"
	@echo "... cell_state.i"
	@echo "... cell_state.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... inference_client.o"
	@echo "... inference_client.i"
	@echo "... inference_client.s"
	@echo "... inference_queue_shm.o"
	@echo "... inference_queue_shm.i"
	@echo "... inference_queue_shm.s"
	@echo "... logger.o"
	@echo "... logger.i"
	@echo "... logger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mcts_agent_selfplay.o"
	@echo "... mcts_agent_selfplay.i"
	@echo "... mcts_agent_selfplay.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... position_pool.o"
	@echo "... position_pool.i"
	@echo "... position_pool.s"
	@echo "... training_shm_writer.o"
	@echo "... training_shm_writer.i"
	@echo "... training_shm_writer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

