# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp/CMakeFiles /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aina/Documents/MCTS-Fanorona/github/tictactoe-alphazero-cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AlphaZero_TTT

# Build rule for target.
AlphaZero_TTT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AlphaZero_TTT
.PHONY : AlphaZero_TTT

# fast build rule for target.
AlphaZero_TTT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/build
.PHONY : AlphaZero_TTT/fast

alphaz_model.o: alphaz_model.cpp.o
.PHONY : alphaz_model.o

# target to build an object file
alphaz_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/alphaz_model.cpp.o
.PHONY : alphaz_model.cpp.o

alphaz_model.i: alphaz_model.cpp.i
.PHONY : alphaz_model.i

# target to preprocess a source file
alphaz_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/alphaz_model.cpp.i
.PHONY : alphaz_model.cpp.i

alphaz_model.s: alphaz_model.cpp.s
.PHONY : alphaz_model.s

# target to generate assembly for a file
alphaz_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/alphaz_model.cpp.s
.PHONY : alphaz_model.cpp.s

board.o: board.cpp.o
.PHONY : board.o

# target to build an object file
board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/board.cpp.o
.PHONY : board.cpp.o

board.i: board.cpp.i
.PHONY : board.i

# target to preprocess a source file
board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/board.cpp.i
.PHONY : board.cpp.i

board.s: board.cpp.s
.PHONY : board.s

# target to generate assembly for a file
board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/board.cpp.s
.PHONY : board.cpp.s

cell_state.o: cell_state.cpp.o
.PHONY : cell_state.o

# target to build an object file
cell_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/cell_state.cpp.o
.PHONY : cell_state.cpp.o

cell_state.i: cell_state.cpp.i
.PHONY : cell_state.i

# target to preprocess a source file
cell_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/cell_state.cpp.i
.PHONY : cell_state.cpp.i

cell_state.s: cell_state.cpp.s
.PHONY : cell_state.s

# target to generate assembly for a file
cell_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/cell_state.cpp.s
.PHONY : cell_state.cpp.s

console_interface.o: console_interface.cpp.o
.PHONY : console_interface.o

# target to build an object file
console_interface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/console_interface.cpp.o
.PHONY : console_interface.cpp.o

console_interface.i: console_interface.cpp.i
.PHONY : console_interface.i

# target to preprocess a source file
console_interface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/console_interface.cpp.i
.PHONY : console_interface.cpp.i

console_interface.s: console_interface.cpp.s
.PHONY : console_interface.s

# target to generate assembly for a file
console_interface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/console_interface.cpp.s
.PHONY : console_interface.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game.cpp.s
.PHONY : game.cpp.s

game_dataset.o: game_dataset.cpp.o
.PHONY : game_dataset.o

# target to build an object file
game_dataset.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game_dataset.cpp.o
.PHONY : game_dataset.cpp.o

game_dataset.i: game_dataset.cpp.i
.PHONY : game_dataset.i

# target to preprocess a source file
game_dataset.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game_dataset.cpp.i
.PHONY : game_dataset.cpp.i

game_dataset.s: game_dataset.cpp.s
.PHONY : game_dataset.s

# target to generate assembly for a file
game_dataset.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/game_dataset.cpp.s
.PHONY : game_dataset.cpp.s

logger.o: logger.cpp.o
.PHONY : logger.o

# target to build an object file
logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/logger.cpp.o
.PHONY : logger.cpp.o

logger.i: logger.cpp.i
.PHONY : logger.i

# target to preprocess a source file
logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/logger.cpp.i
.PHONY : logger.cpp.i

logger.s: logger.cpp.s
.PHONY : logger.s

# target to generate assembly for a file
logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/logger.cpp.s
.PHONY : logger.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/main.cpp.s
.PHONY : main.cpp.s

mcts_agent.o: mcts_agent.cpp.o
.PHONY : mcts_agent.o

# target to build an object file
mcts_agent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/mcts_agent.cpp.o
.PHONY : mcts_agent.cpp.o

mcts_agent.i: mcts_agent.cpp.i
.PHONY : mcts_agent.i

# target to preprocess a source file
mcts_agent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/mcts_agent.cpp.i
.PHONY : mcts_agent.cpp.i

mcts_agent.s: mcts_agent.cpp.s
.PHONY : mcts_agent.s

# target to generate assembly for a file
mcts_agent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/mcts_agent.cpp.s
.PHONY : mcts_agent.cpp.s

minimax_agent.o: minimax_agent.cpp.o
.PHONY : minimax_agent.o

# target to build an object file
minimax_agent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/minimax_agent.cpp.o
.PHONY : minimax_agent.cpp.o

minimax_agent.i: minimax_agent.cpp.i
.PHONY : minimax_agent.i

# target to preprocess a source file
minimax_agent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/minimax_agent.cpp.i
.PHONY : minimax_agent.cpp.i

minimax_agent.s: minimax_agent.cpp.s
.PHONY : minimax_agent.s

# target to generate assembly for a file
minimax_agent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/minimax_agent.cpp.s
.PHONY : minimax_agent.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AlphaZero_TTT.dir/build.make CMakeFiles/AlphaZero_TTT.dir/player.cpp.s
.PHONY : player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... AlphaZero_TTT"
	@echo "... alphaz_model.o"
	@echo "... alphaz_model.i"
	@echo "... alphaz_model.s"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... cell_state.o"
	@echo "... cell_state.i"
	@echo "... cell_state.s"
	@echo "... console_interface.o"
	@echo "... console_interface.i"
	@echo "... console_interface.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... game_dataset.o"
	@echo "... game_dataset.i"
	@echo "... game_dataset.s"
	@echo "... logger.o"
	@echo "... logger.i"
	@echo "... logger.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mcts_agent.o"
	@echo "... mcts_agent.i"
	@echo "... mcts_agent.s"
	@echo "... minimax_agent.o"
	@echo "... minimax_agent.i"
	@echo "... minimax_agent.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

